### ISSUE TITLE
comments

### ISSUE THREAD

**Issue by zeinalii** [data301-2020-winter2/course-project-group_1017#2]
## High priority (must-fix)

- [x] Make sure to use only one single project_functions.py. Call the function from Analysis/scripts/project_functions.py
- [x] Use relative path. the following path is not accepted:
address = '/Users/rylanvandermeulen/Desktop/course-project-group_1017/Data/Raw/medical_expenses.csv'

- [x] call your data from Data/raw/ folder instead of online link.

**Comment by hughfb99** [comment]
Each group memeber fixed the issues in their folders
